In [1]:
import pandas as pd

In [3]:
sinh_vien = {
    'ten': ten_sv,
    'huyen': huyen_sv,
    'xa': xa_sv,
    'thon': thon_sv
}

In [2]:
ten_sv = ['Minh Tri', 'Nhat Minh', 'Van Thang', 'Minh']
huyen_sv = ['Thành phố Huế', 'Thành phố Huế', 'Thành phố Huế', 'Thành phố Huế']
xa_sv = ['Phường Hương Long', 'Phường Vĩnh Ninh', 'Phường Kim Long', 'Phường Hương Long']
thon_sv = ['Tổ dân phố 4','Tổ dân phố 2','Tổ dân phố 8', 'Tổ dân phố 4']

In [5]:
df_sv = pd.DataFrame(sinh_vien)

In [6]:
df_sv

         ten          huyen                 xa           thon
0   Minh Tri  Thành phố Huế  Phường Hương Long   Tổ dân phố 4
1  Nhat Minh  Thành phố Huế   Phường Vĩnh Ninh   Tổ dân phố 2
2  Van Thang  Thành phố Huế    Phường Kim Long  Tổ dân phố 8
3       Minh  Thành phố Huế  Phường Hương Long   Tổ dân phố 4

In [9]:
df = pd.read_csv('ban_mau_2.csv')

In [10]:
df

                 huyen             xa                  thon  cap
0        Thành phố Huế   Xã Hương Thọ         Thôn Định Môn    1
1        Thành phố Huế   Xã Hương Thọ          Thôn Hòa An    1
2        Thành phố Huế   Xã Hương Thọ         Thôn Kim Ngọc    1
3        Thành phố Huế   Xã Hương Thọ       Thôn La Khê Bãi    1
4        Thành phố Huế   Xã Hương Thọ      Thôn La Khê Trẹm    1
...                ...            ...                   ...  ...
1102  Thị xã Hương Trà  Xã Hương Toàn        Thôn Giáp Đông    2
1103  Thị xã Hương Trà  Xã Hương Toàn         Thôn Giáp Tây    2
1104  Thị xã Hương Trà  Xã Hương Toàn      Thôn Giáp Thượng    2
1105  Thị xã Hương Trà  Xã Hương Toàn  Thôn Triều Sơn Trung    2
1106  Thị xã Hương Trà  Xã Hương Toàn      Thôn Liễu Cốc Hạ    3

[1107 rows x 4 columns]

In [11]:
pd.merge(df_sv, df, on=["huyen", "xa", "thon"])

         ten          huyen                 xa           thon  cap
0   Minh Tri  Thành phố Huế  Phường Hương Long   Tổ dân phố 4    3
1       Minh  Thành phố Huế  Phường Hương Long   Tổ dân phố 4    3
2  Nhat Minh  Thành phố Huế   Phường Vĩnh Ninh   Tổ dân phố 2    2
3  Van Thang  Thành phố Huế    Phường Kim Long  Tổ dân phố 8    1